name: Announcer
version: 1.2.2
main: com.example.AnnouncerPlugin
api-version: 1.20
author: crysuchi, 4uchi
description: Simple chat announcer and scheduler.
website: https://github.com/crysuchi/Announcer
commands:
  announcer:
    description: Main command for the Announcer plugin
    usage: /announcer [reload|credits]
    permission: announcer.use
permissions:
  announcer.use:
    description: Allows use of the /announcer command
    default: true

softdepend: [PlaceholderAPI]
